### ISSUE TITLE
putting me into afk

### ISSUE THREAD

**Issue by imaxisXD** [NiciusB/twitch-drops-lurker#4]
script put me in afk mode and getting this error when switching streamer

(node:7752) UnhandledPromiseRejectionWarning: Error: net::ERR_ABORTED at https://www.twitch.tv/blue_mx
    at navigate (E:\drop\node_modules\puppeteer-core\lib\FrameManager.js:120:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async FrameManager.navigateFrame (E:\drop\node_modules\puppeteer-core\lib\FrameManager.js:94:17)
    at async Frame.goto (E:\drop\node_modules\puppeteer-core\lib\FrameManager.js:406:12)
    at async Page.goto (E:\drop\node_modules\puppeteer-core\lib\Page.js:672:12)
    at async goToRandomLiveStreamer (E:\drop\src\index.js:32:3)
    at async Timeout._onTimeout (E:\drop\src\index.js:72:7)
  -- ASYNC --
    at Frame.<anonymous> (E:\drop\node_modules\puppeteer-core\lib\helper.js:111:15)
    at Page.goto (E:\drop\node_modules\puppeteer-core\lib\Page.js:672:49)
    at Page.<anonymous> (E:\drop\node_modules\puppeteer-core\lib\helper.js:112:23)
    at goToRandomLiveStreamer (E:\drop\src\index.js:32:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Timeout._onTimeout (E:\drop\src\index.js:72:7)
(node:7752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7752) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by NiciusB** [comment]
It seems like either twitch servers or your internet connection had a small network disruption.
Currently, it should fix itself after max 1 hour. I'll take a look at the code and see how can I improve the reconnection time
